version: '3.8'
services:
  db:
    container_name: 'foodbook_mariadb'
    image: 'mariadb:10.7.3'
    ports:
      - '127.0.0.1:3306:3306'
    env_file: '.docker.env'
    volumes:
      - 'mariadb:/var/lib/mysql'

volumes:
  mariadb: