version: '3.8'
services:
  db:
    container_name: 'foodbook_mariadb'
    image: mariadb:latest
    env_file: '.docker.env'
    volumes:
      - mariadb:/var/lib/mysql

  frontend:
    container_name: 'foodbook_frontend'
    image: 'ghcr.io/julianjesacher/foodbook/foodbook-frontend:latest'
    ports:
      - '127.0.0.1:3000:80'
    environment:
      - 'SERVER_HOST=https://api.foodbook.julianjesacher.dev'
    volumes:
      - ./assets:/usr/share/nginx/html/assets

  backend:
    container_name: 'foodbook_backend'
    image: 'ghcr.io/julianjesacher/foodbook/foodbook-backend:latest'
    env_file: '.docker.env'
    environment:
      - 'TYPEORM_DB_HOST=db'
      - 'FRONTEND_HOST=*'
    ports:
      - '127.0.0.1:3001:3000'
    depends_on:
      - 'db'

volumes:
  mariadb:
